config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'new', to: 'games#new'

  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
require 'open-uri'
require 'json'

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @letters = generate_letters(10)
  end
    def generate_letters(size)
      Array.new(size) { ('A'..'Z').to_a.sample }
    end

  def score
    @word = params[:word].upcase
    @letters = params[:letter]&.split(" ") || []

    if valid_from_grid?(@word, @letters)
      if valid_english_word?(@word)
        @result = "Congratulations! #{@word} is a valid English word."
      else
        @result = "Sorry, but #{@word} is not a valid English word."
      end
    else
      @result = "Sorry, but #{@word} can't be built from #{@letters.join(', ')}."
    end
  end

    def valid_from_grid?(word, letters)
      word.chars.all? { |letter| word.count(letter) <= letters.count(letter) }
    end

    def valid_english_word?(word)
      url = "https://dictionary.lewagon.com/#{word}"
      response = URI.open(url).read
      json = JSON.parse(response)
      json['found']
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>NEW</h1>
<p><%= @letters.join(" ") %></p>

<%= form_with url: score_path, method: :post, data: { turbo: false } do %>
  <%= text_field_tag :word, nil, class: "form-control", placeholder: "Type your word here..." %>
  <%= hidden_field_tag :letter, @letters.join(" ") %>
  <%= submit_tag "Play", class: "btn btn-primary" %>
<% end %>

app/views/games/score.html.erb
<h1>Result</h1>

<p><strong>Your word:</strong> <%= @word %></p>
<p><strong>Grid letters:</strong> <%= @letters.join(", ") %></p>
<p><strong>Result:</strong> <%= @result %></p>

<%= link_to "Play again", new_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>